# Common
namespace:
  name: springboot

labels:
   application: springboot-app


#Pod
Podname: springboot-pod

#deployment
deploymentname: springboot-deployment
spec:
  replicas: 3
  containers:
    name: springboot-container
    image: tharun13055/springboot-app:latest
    imagePullPolicy: Always
    ports: 8080
resources:
  requests:
    cpu: "256m"
    memory: "1Gi"
  limits:
    cpu: "512m"
    memory: "1Gi"


# service 
servicename: springboot-service
servicespec:
  protocol: TCP
  port: 80
  type: LoadBalancer
  

serviceaccountname: service-account
rolebindingname: springboot-rolebindings


# Role
rolename: springboot-role
rules:
  - apiGroups: ["*"]
    resources: ["pods","deployments","services","namespaces","horizontalpodautoscalers"]
    verbs: ["create","get","update","delete","list","log","run","watch"]

# HPA
hpaname: springboot-hpa
hpaspec:
  minReplicas: 2
  maxReplicas: 10
metrics:
  type: Resource
  name: cpu
  target: 
    type: Utilization
    averageUtilization: 50