name: owasp-dependency
description: It is used to check the pom.xml package
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project with Maven
      run: mvn clean install
      shell: bash
    - name: Dependencycheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'springboot-app'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
          name: Depcheck report
          path: ${{github.workspace}}/reports