name: Maven jar file build

description: this will build the maven jar file

runs:
  using: composite

  steps:
    - name: install java-maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: install Maven
      run: |
          sudo apt update
          sudo apt install maven -y
      shell: bash

    - name: maven test
      run: mvn test
      shell: bash

    - name: maven verify
      run: mvn verify -DskipUnitTests
      shell: bash

    - name: maven compile
      run: mvn clean compile
      shell: bash

    - name: maven package
      run: mvn clean package
      shell: bash
    
    - name: upload artifactory
      uses: actions/upload-artifact@v3
      with:
        name: jar-file
        path: /jar