name: Maven jar file build

description: this will build the maven jar file

runs:
  using: composite

  steps:
    - name: install java-maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: install Maven
      run: |
          sudo apt update
          sudo apt install maven -y
      shell: bash
    # - name: Cache Maven Dependencies
    #   id: maven-cache
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.m2/repository
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: maven package
      run: mvn clean package
      shell: bash
    
    - name: upload artifactory
      uses: actions/upload-artifact@v3
      with:
        name: jar-file
        path: ./target/*.jar