apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rolename}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
  namespace: {{ .Values.namespace.name}}
rules:
  apiGroups: ['']
  resources: {{ .Values.rules.resources}}
  verbs: {{ .Values.rules.verbs}}