apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-rolebinding
  labels:
    kubernetes.io/name: service-account
  namespace: springboot
roleRef:
  apiGroups: ''
  kind: Role
  name: spring-role
subjects:
  kind: ServiceAccount
  name: spring-serviceaccount
  namespace: springboot