apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rolebindingname}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
  namespace: springboot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rolename}}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccountname}}
    namespace: {{ .Values.namespace.name}}