apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccountname}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
  namespace: {{ .Values.namespace.name}}
  automountServiceAccountToken: false
  
