apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  labels:
    kubernetes.io/name: service-account
  namespace: springboot
spec:
  name: spring-service-account
  automountServiceAccountToken: false
  
