name: To create Docker image and Push

description: in this action we create docker image and push to the dockerhub

runs:
  using: composite
  
  steps:
    - name: Download jar file 
      uses: actions/download-artifact@v3
      with: 
        name: jar-file

    - name: Get the latest tag
      id: get_latest_tag
      run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"
      shell: bash

    - name: Increment the tag number
      id: increment_tag
      run: echo "::set-output name=tag::$(echo ${TAG#v} | awk -F. -v OFS=. '{$NF=$NF+1;} 1')"
      shell: bash
    
    - name: Docker image build
      run: |
        docker build -t tharun13055/springboot-app:lastest .
        docker build -t tharun13055/springboot-app:${{ steps.increment_tag.outputs.tag }} .
      shell: bash
    
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.11.2
      with:
        image-ref: 'tharun13055/springboot-app:lastest'
        security-checks: 'vuln,secret,config'
        format: 'sarif'
        args: '--ignore-unfixed'
        output: 'trivy-image-results.sarif'
        severity: ''

    - name: Upload Trivy Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-image-results.sarif'
        ref: ${{ github.ref }}
        sha: ${{ github.sha }}

    
    - name: docker image Push
      run: |
        docker push tharun13055/springboot-app:lastest
        docker push tharun13055/springboot-app:${{ steps.increment_tag.outputs.tag }}
      shell: bash

