name: Nexus jar push

description: it will push the jar file to nexus

runs:
  using: composite

  steps:
    - name: artifactory download
      uses: actions/download-artifact@v3
      with:
        name: jar-file
        path: /target/springboot-app.jar

    - name: Upload to Nexus or Artifactory
      run: |
        mvn deploy:deploy-file
          -Dfile=target/springboot-app.jar
          -DrepositoryId=nexus
          -Durl=${{ secrets.NEXUS_URL }}
          -DgeneratePom=false
          -Dpackaging=jar
          -DgroupId=com.abhishek 
          -DartifactId=spring-boot-demo
          -Dversion=1.0  
          -DgeneratePom.description="this project is build in maven"  
          -Drepository.url=${{ secrets.NEXUS_URL }}/repository/nexus/
          -Drepository.username=${{ secrets.NEXUS_USERNAME }}
          -Drepository.password=${{ secrets.NEXUS_PASSWORD }}
      shell: bash
