name: Nexus jar push

description: it will push the jar file to nexus

runs:
  using: composite

  steps:
    - name: artifactory download
      uses: actions/download-artifact@v3
      with:
        name: jar-file
        path: /target/springboot-app.jar
