name: Nexus jar push

description: it will push the jar file to nexus

runs:
  using: composite
  steps:
    - name: github checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn package --file pom.xml
      shell: bash