name: maven-springboot-project

on: workflow_dispatch

jobs:
  maven-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Maven jar package
        uses: ./.github/actions/maven-jar

  sample:
    runs-on: ubuntu-22.04
    needs: docker
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: docker-push-scan
        uses: ./.github/actions/docker
        
