name: maven-springboot-project

on: workflow_dispatch

jobs:
  maven-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Maven jar package
        uses: ./.github/actions/maven-jar

  Sonarqube:
    runs-on: ubuntu-22.04
    needs: maven-build
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Sonarqube scanner
        uses: ./.github/actions/sonarqube
    
  docker:
    runs-on: ubuntu-22.04
    needs: Sonarqube
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: docker-push-scan
        uses: ./.github/actions/docker

        
