name: maven-springboot-project

on: workflow_dispatch

jobs:
  maven-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Maven jar package
        uses: ./.github/actions/maven-jar

  # maven-dep-check:
  #   runs-on: ubuntu-22.04
  #   needs: maven-build
  #   steps:
  #   - name: Git Checkout
  #     uses: actions/checkout@v3
  #   - name: dependency-check
  #     uses: ./.github/actions/owasp

  # Sonarqube:
  #   runs-on: ubuntu-22.04
  #   needs: maven-build
  #   steps:
  #     - name: Git Checkout
  #       uses: actions/checkout@v3
  #     - name: Sonarqube scanner
  #       uses: ./.github/actions/sonarqube
  #     - name: Build and analyze
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #       run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=javaspringboot

  # docker:
  #   runs-on: ubuntu-22.04
  #   needs: maven-build
  #   steps:
  #     - name: Git Checkout
  #       uses: actions/checkout@v3
  #     - name: Docker login
  #       env:
  #         DOCKER_USER: ${{ secrets.DOCKER_USER }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #       run: |
  #         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  #       shell: bash
  #     - name: docker-push-scan
  #       uses: ./.github/actions/docker
  
  nexus:
    runs-on: ubuntu-22.04
    needs: maven-build
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: nexus jar push
        uses: ./.github/actions/nexus
      - name: list
        run: tree
        shell: bash

      - name: Upload to Nexus or Artifactory
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn deploy:deploy-file
            -Dfile=springboot-app.jar
            -DrepositoryId=nexus
            -Durl=$NEXUS_URL
            -DgeneratePom=false
            -Dpackaging=jar
            -DgroupId=com.abhishek 
            -DartifactId=spring-boot-demo
            -Dversion=1.0  
            -DgeneratePom.description="this project is build in maven"  
            -Drepository.url=$NEXUS_URL/repository/nexus/
            -Drepository.username=$NEXUS_USERNAME
            -Drepository.password=$NEXUS_PASSWORD
        shell: bash


        
