name: terraform kuberentes
on: workflow_dispatch
jobs:
  terraform:
    runs-on: ubuntu-22.04
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TF_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_TENANT_ID }}
          subscription-id: ${{ secrets.TF_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan -var "client_id=${{ secrets.TF_CLIENT_ID }}" -var "tenant_id=${{ secrets.TF_TENANT_ID }}" -var "subscription_id={{secrets.TF_SUBSCRIPTION_ID}}" -var "client_secret={{secrets.TF_CLIENT_SECRET}}"

      - name: Terraform Apply
        run: |
          terraform apply --auto-approve -var "client_id=${{ secrets.TF_CLIENT_ID }}" -var "tenant_id=${{ secrets.TF_TENANT_ID }}" -var "subscription_id={{secrets.TF_SUBSCRIPTION_ID}}" -var "client_secret={{secrets.TF_CLIENT_SECRET}}"
