name: terraform kuberentes
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Terraform plan or apply'
        default: 'apply'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TF_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_TENANT_ID }}
          subscription-id: ${{ secrets.TF_SUBSCRIPTION_ID }}
      
      - name: Azure command
        run: |
          az account show
          az group list
        shell: bash

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          terraform init
          terraform validate
        working-directory: ./terraform


      - name: Terraform Plan
        run: |
          terraform ${{ github.event.inputs.name }} -var "subscription_id=${{ secrets.TF_SUBSCRIPTION_ID }}" -var "client_id=${{ secrets.TF_CLIENT_ID }}" -var "tenant_id=${{ secrets.TF_TENANT_ID }}" -var "client_secret=${{ secrets.TF_CLIENT_SECRET }}"
        working-directory: ./terraform

      # - name: Terraform Apply
      #   run: |
      #     terraform ${{ github.event.inputs.name }} --auto-approve -var "subscription_id=${{ secrets.TF_SUBSCRIPTION_ID }}" -var "client_id=${{ secrets.TF_CLIENT_ID }}" -var "tenant_id=${{ secrets.TF_TENANT_ID }}" -var "client_secret=${{ secrets.TF_CLIENT_SECRET }}"
      #   working-directory: ./terraform

        